In [2]:
import numpy as np

In [3]:
def sigmoid (no):
    e = 2.718281828459045
    return 1/(1+e**(-no))

In [4]:
print (sigmoid(0))

0.5


In [5]:
def sigmoid_inv (no):
    return np.log(no/(1-no))

In [6]:
weights = np.ones([5,5]) 

#1st column is coeff b/w ans and first layer
#In r th row, cell with coulmn i is the weight from i th input to r th neuron in first layer
# Last row for bias

In [7]:
print (weights)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
derivative = np.ones([5,5])

# Each contains factor which has to be multiplied by learning rate to update the weight

In [9]:
print (derivative)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
answer = np.ones(5)

# 0th is final answer
# rest ith is ith neuron's output

In [11]:
print (answer)

[1. 1. 1. 1. 1.]


In [12]:
data = np.array([0,1,-15,10])
expected = 2
alpha = np.array([0.0001,0.0001,0.0001,0.0001,0.0001])

#Test Data

In [1]:
# To set answer based on input
#Take "data" as array of input parameters

a = 0

while a < 100000:
      
    # data -> 1st Layer
    
    for i in range (1,5):
        temp = 0    
        for j in range(4):
            temp = temp + weights[j,i] * data[j]
        temp = temp + weights [4,i] * 1
        answer[i] = sigmoid(temp)
       
    # 1st Layer -> Answer
    
    temp = 0
    for i in range (4):
        temp = temp + weights[i,0] * answer[i+1]
    temp = temp + weights[4,0] * 1
    answer[0]= sigmoid(temp)
    
    # Cost Function
    
    Cost_curr = ( answer[0] - sigmoid(expected) ) ** 2

    # Starting to set derivative by common term
    
    derivative = np.ones([5,5])
    derivative = derivative * 2 * ( answer[0] - sigmoid(expected) )

    # Updating Layer 1 -> Answer Weights

    for i in range (4):
        derivative[i,0] = answer[0] ** 2 * ( 1/answer[0] - 1 ) * answer[i+1]
    derivative[4,0] = answer[0] ** 2 * ( 1/answer[0] - 1 ) * 1

    # Updating Input -> Layer 1 Weights

    for i in range(1,5):
        for j in range (4): 
            temp1 = 0
            for k in range (4):
                temp1 = temp1 + weights[k,0] * answer[k+1] ** 2 * ( 1/answer[k+1] - 1 ) * data [k]
            derivative[j,i] = derivative[j,i] * answer[0] ** 2 * ( 1/answer[0] - 1 ) * temp1
        for k in range (4):
            temp1 = temp1 + weights[k,0] * answer[k+1] ** 2 * ( 1/answer[k+1] - 1 ) * 1
        derivative[4,i] = derivative[4,i] * answer[0] ** 2 * ( 1/answer[0] - 1 ) * temp1

    # Being on a minima
    
#     if a > 5:
#         if Cost_curr > Cost_prev:
#             print ("Hi")
#             break
    
    # Updting Weights
    
    for i in range (5):
        weights[:,i] = weights[:,i] - alpha[i] * derivative[:,i]
        
    Cost_prev = Cost_curr 
    
    # Iterator
    
    a = a + 1
    print (answer[0])

NameError: name 'weights' is not defined

In [14]:
print ( (sigmoid(2) - answer[0]) ** 2 )
print ("\n")
print (answer)
print ("\n")
print (answer)
print ("\n")
print (weights)
print ("\n")
print (derivative)
print (sigmoid(expected)**2)

0.22807324456199324


[0.40322693 0.30056174 0.30056174 0.30056174 0.30056174]


[0.40322693 0.30056174 0.30056174 0.30056174 0.30056174]


[[ 0.76905607  0.46114122  0.46114122  0.46114122  0.46114122]
 [ 0.76905607  0.46114122  0.46114122  0.46114122  0.46114122]
 [ 0.76905607  0.46114122  0.46114122  0.46114122  0.46114122]
 [ 0.76905607  0.46114122  0.46114122  0.46114122  0.46114122]
 [-1.3166655   1.          1.          1.          1.        ]]


[[7.23256671e-02 1.48638418e-01 1.48638418e-01 1.48638418e-01
  1.48638418e-01]
 [7.23256671e-02 1.48638418e-01 1.48638418e-01 1.48638418e-01
  1.48638418e-01]
 [7.23256671e-02 1.48638418e-01 1.48638418e-01 1.48638418e-01
  1.48638418e-01]
 [7.23256671e-02 1.48638418e-01 1.48638418e-01 1.48638418e-01
  1.48638418e-01]
 [2.40634973e-01 8.93108427e-17 8.93108427e-17 8.93108427e-17
  8.93108427e-17]]
0.7758034925743758


In [15]:
def Cost (predicted, actual):
    return (predicted-actual)**2

In [16]:
print (a)

100000


In [17]:
print (sigmoid(2))

0.8807970779778823


In [18]:
print (answer[0])

0.40322693175641544


In [19]:
sigmoid_inv (answer[0])

-0.3920374113763444